import { School } from './types';

export const SCHOOL_DATA: School[] = [
  {
    id: 'sd-minnatul-huda',
    name: 'SD Minnatul Huda',
    logo: 'https://imgur.com/4hdcTD7.png',
    description: 'Membentuk generasi cerdas, berakhlak mulia, dan berprestasi sejak dini dengan kurikulum terpadu dan lingkungan belajar yang menyenangkan.',
    summary: {
      foundedYear: 2010,
      headmaster: 'Dr. Aisyah S.Pd.I',
    },
    vision: "Menjadi sekolah dasar Islam unggulan yang mencetak generasi Qur'ani, cerdas, kreatif, dan berakhlak karimah.",
    mission: [
      "Menyelenggarakan pendidikan berkualitas yang mengintegrasikan kurikulum nasional dan nilai-nilai Islam.",
      "Mengembangkan potensi siswa di bidang akademik, non-akademik, dan keagamaan.",
      "Membiasakan siswa dengan akhlak mulia dalam kehidupan sehari-hari.",
      "Menciptakan lingkungan belajar yang aman, nyaman, dan Islami.",
    ],
    featuredPrograms: [
      { icon: 'book', title: 'Tahfidz Al-Qur\'an', description: 'Program hafalan Al-Qur\'an intensif dengan target juz 30 sebagai standar kelulusan.' },
      { icon: 'globe', title: 'Kelas Bilingual', description: 'Pembelajaran menggunakan dua bahasa (Indonesia & Inggris) untuk mempersiapkan siswa di era global.' },
      { icon: 'leaf', title: 'Pendidikan Karakter', description: 'Program pembentukan karakter Islami melalui kegiatan harian, teladan, dan pembiasaan.' },
    ],
    statistics: {
      students: 450,
      alumni: 1200,
      teachers: 35,
      achievements: 150,
      extracurriculars: 12,
    },
    mainImage: 'https://picsum.photos/seed/sd-main/1200/800',
    youtubeThumbnail: 'https://picsum.photos/seed/sd-yt/800/450',
    youtubeUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    gallery: [
      'https://picsum.photos/seed/sd-gal1/400/300',
      'https://picsum.photos/seed/sd-gal2/400/300',
      'https://picsum.photos/seed/sd-gal3/400/300',
      'https://picsum.photos/seed/sd-gal4/400/300',
      'https://picsum.photos/seed/sd-gal5/400/300',
      'https://picsum.photos/seed/sd-gal6/400/300',
    ],
    achievements: [
      {
        image: 'https://picsum.photos/seed/sd-ach1/400/400',
        title: 'Juara 1 Olimpiade Sains Nasional',
        level: 'Nasional',
        date: '15 Agustus 2023',
        description: 'Meraih medali emas dalam kompetisi sains paling bergengsi tingkat nasional.',
      },
      {
        image: 'https://picsum.photos/seed/sd-ach2/400/400',
        title: 'Juara Umum Lomba Cerdas Cermat',
        level: 'Provinsi',
        date: '22 Juni 2023',
        description: 'Menunjukkan keunggulan dalam pengetahuan umum dan kecepatan berpikir.',
      },
    ],
    detailsUrl: '#',
    accentColor: 'border-emerald-500',
    textColor: 'text-emerald-600',
  },
  {
    id: 'smp-minnatul-huda',
    name: 'SMP Minnatul Huda',
    logo: 'https://imgur.com/4hdcTD7.png',
    description: 'Mengembangkan potensi siswa secara akademis dan non-akademis, mempersiapkan mereka menjadi pribadi yang tangguh dan inovatif.',
    summary: {
      foundedYear: 2005,
      headmaster: 'Bambang Sutrisno, M.Pd',
    },
    vision: "Terwujudnya sekolah yang menghasilkan lulusan berprestasi, berdaya saing, inovatif, dan berlandaskan iman dan taqwa.",
    mission: [
      "Melaksanakan pembelajaran aktif, inovatif, kreatif, efektif, dan menyenangkan (PAIKEM).",
      "Mengembangkan potensi siswa sesuai bakat dan minat melalui kegiatan ekstrakurikuler.",
      "Membina kemandirian dan jiwa kepemimpinan siswa melalui organisasi.",
      "Meningkatkan prestasi di bidang akademik dan non-akademik di tingkat regional dan nasional.",
    ],
    featuredPrograms: [
      { icon: 'lab', title: 'Science & Robotic Club', description: 'Wadah eksplorasi sains dan teknologi melalui eksperimen dan pembuatan robot.' },
      { icon: 'speaker', title: 'Public Speaking & Leadership', description: 'Pelatihan untuk meningkatkan kepercayaan diri, kemampuan berbicara di depan umum, dan kepemimpinan.' },
      { icon: 'briefcase', title: 'Career Orientation', description: 'Program pengenalan dunia kerja dan perguruan tinggi untuk merencanakan masa depan.' },
    ],
    statistics: {
      students: 620,
      alumni: 2500,
      teachers: 50,
      achievements: 210,
      extracurriculars: 18,
    },
    mainImage: 'https://picsum.photos/seed/smp-main/1200/800',
    youtubeThumbnail: 'https://picsum.photos/seed/smp-yt/800/450',
    youtubeUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    gallery: [
      'https://picsum.photos/seed/smp-gal1/400/300',
      'https://picsum.photos/seed/smp-gal2/400/300',
      'https://picsum.photos/seed/smp-gal3/400/300',
      'https://picsum.photos/seed/smp-gal4/400/300',
      'https://picsum.photos/seed/smp-gal5/400/300',
      'https://picsum.photos/seed/smp-gal6/400/300',
    ],
    achievements: [
      {
        image: 'https://picsum.photos/seed/smp-ach1/400/400',
        title: 'Medali Perak Kompetisi Robotik',
        level: 'Internasional',
        date: '10 Desember 2023',
        description: 'Berhasil merancang dan memprogram robot yang kompetitif di tingkat dunia.',
      },
      {
        image: 'https://picsum.photos/seed/smp-ach2/400/400',
        title: 'Juara 1 Festival Seni Budaya',
        level: 'Nasional',
        date: '05 November 2023',
        description: 'Menampilkan pertunjukan tari tradisional yang memukau dewan juri.',
      },
    ],
    detailsUrl: '#',
    accentColor: 'border-teal-500',
    textColor: 'text-teal-600',
  },
  {
    id: 'smk-minnatul-huda',
    name: 'SMA / SMK Minnatul Huda',
    logo: 'https://imgur.com/4hdcTD7.png',
    description: 'Menyiapkan lulusan yang siap kerja dan siap kuliah, dengan keahlian spesifik dan wawasan global untuk menghadapi tantangan masa depan.',
    summary: {
      foundedYear: 2008,
      headmaster: 'Ir. H. Joko Widodo, M.T.',
    },
    vision: "Menjadi lembaga pendidikan kejuruan yang menghasilkan lulusan kompeten, profesional, berjiwa wirausaha, dan berakhlak mulia.",
    mission: [
      "Menyelenggarakan pendidikan kejuruan yang relevan dengan kebutuhan industri dan dunia kerja (IDUKA).",
      "Membekali siswa dengan keterampilan teknis (hard skills) dan non-teknis (soft skills).",
      "Membangun kerjasama strategis dengan industri untuk program magang dan penyerapan lulusan.",
      "Menumbuhkan semangat kewirausahaan dan kemandirian pada siswa.",
    ],
    featuredPrograms: [
      { icon: 'computer', title: 'Digital Marketing', description: 'Jurusan yang fokus pada pemasaran online, SEO, SEM, dan media sosial untuk industri modern.' },
      { icon: 'tools', title: 'Teknik Kendaraan Ringan', description: 'Program keahlian otomotif dengan fasilitas bengkel modern dan kerjasama industri.' },
      { icon: 'briefcase', title: 'Job Matching & Incubator', description: 'Program penyaluran kerja dan inkubator bisnis untuk siswa yang ingin berwirausaha setelah lulus.' },
    ],
    statistics: {
      students: 800,
      alumni: 3100,
      teachers: 75,
      achievements: 300,
      extracurriculars: 25,
    },
    mainImage: 'https://picsum.photos/seed/smk-main/1200/800',
    youtubeThumbnail: 'https://picsum.photos/seed/smk-yt/800/450',
    youtubeUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    gallery: [
      'https://picsum.photos/seed/smk-gal1/400/300',
      'https://picsum.photos/seed/smk-gal2/400/300',
      'https://picsum.photos/seed/smk-gal3/400/300',
      'https://picsum.photos/seed/smk-gal4/400/300',
      'https://picsum.photos/seed/smk-gal5/400/300',
      'https://picsum.photos/seed/smk-gal6/400/300',
    ],
    achievements: [
      {
        image: 'https://picsum.photos/seed/smk-ach1/400/400',
        title: 'Pemenang Lomba Kompetensi Siswa',
        level: 'Nasional',
        date: '01 Oktober 2023',
        description: 'Juara dalam bidang Desain Grafis, menunjukkan kreativitas dan skill teknis.',
      },
      {
        image: 'https://picsum.photos/seed/smk-ach2/400/400',
        title: 'Best Startup Idea Competition',
        level: 'Provinsi',
        date: '20 September 2023',
        description: 'Mengembangkan ide bisnis berbasis teknologi yang solutif dan inovatif.',
      },
    ],
    detailsUrl: '#',
    accentColor: 'border-green-500',
    textColor: 'text-green-600',
  },
  {
    id: 'yayasan-minnatul-huda',
    name: 'Yayasan Minnatul Huda',
    logo: 'https://imgur.com/4hdcTD7.png',
    description: 'Berkomitmen pada pengabdian masyarakat melalui pendidikan berkualitas, program sosial, dan pemberdayaan umat.',
    summary: {
      foundedYear: 1998,
      headmaster: 'KH. Abdullah Said',
    },
    vision: "Menjadi yayasan Islam terdepan dalam membangun peradaban melalui pendidikan, dakwah, dan pemberdayaan sosial ekonomi umat.",
    mission: [
      "Menyediakan layanan pendidikan yang terjangkau dan berkualitas untuk semua lapisan masyarakat.",
      "Mengelola dana ZISWAF (Zakat, Infaq, Shadaqah, Wakaf) secara profesional dan amanah.",
      "Melaksanakan program dakwah yang mencerahkan dan menyejukkan.",
      "Memberdayakan ekonomi masyarakat melalui program pelatihan dan bantuan modal usaha.",
    ],
    featuredPrograms: [
      { icon: 'heart', title: 'Layanan Sosial & Kesehatan', description: 'Program bantuan untuk dhuafa, yatim, serta layanan kesehatan gratis bagi masyarakat.' },
      { icon: 'users', title: 'Pemberdayaan Ekonomi Umat', description: 'Pelatihan skill, bantuan modal usaha mikro, dan pembinaan UMKM di lingkungan pesantren.' },
      { icon: 'book', title: 'Kajian Islam & Dakwah Digital', description: 'Menyebarkan nilai-nilai Islam melalui kajian rutin, seminar, dan konten dakwah di platform digital.' },
    ],
    statistics: {
      students: 1870,
      alumni: 6800,
      teachers: 160,
      achievements: 660,
      extracurriculars: 5,
    },
    mainImage: 'https://picsum.photos/seed/yayasan-main/1200/800',
    youtubeThumbnail: 'https://picsum.photos/seed/yayasan-yt/800/450',
    youtubeUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    gallery: [
      'https://picsum.photos/seed/yayasan-gal1/400/300',
      'https://picsum.photos/seed/yayasan-gal2/400/300',
      'https://picsum.photos/seed/yayasan-gal3/400/300',
      'https://picsum.photos/seed/yayasan-gal4/400/300',
      'https://picsum.photos/seed/yayasan-gal5/400/300',
      'https://picsum.photos/seed/yayasan-gal6/400/300',
    ],
    achievements: [
      {
        image: 'https://picsum.photos/seed/yayasan-ach1/400/400',
        title: 'Penghargaan Yayasan Peduli Pendidikan',
        level: 'Nasional',
        date: '10 Januari 2024',
        description: 'Diakui atas kontribusi signifikan dalam meningkatkan akses dan mutu pendidikan.',
      },
      {
        image: 'https://picsum.photos/seed/yayasan-ach2/400/400',
        title: 'Program Desa Binaan Terbaik',
        level: 'Provinsi',
        date: '12 November 2023',
        description: 'Sukses dalam program pemberdayaan ekonomi dan sosial masyarakat desa.',
      },
    ],
    detailsUrl: '#',
    accentColor: 'border-stone-500',
    textColor: 'text-stone-600',
  },
];