// constants.ts
// FIX: Import School type and define/export SCHOOL_DATA
import { GalleryItem, School } from './types';

export const SCHOOL_DATA: School[] = [
  {
    id: 'sd-minnatul-huda',
    name: 'SD Minnatul Huda',
    description: 'Mencetak generasi Qur\'ani yang cerdas, berakhlak mulia, dan berprestasi.',
    logo: 'https://imgur.com/4hdcTD7.png',
    accentColor: 'border-blue-500',
    textColor: 'text-blue-600',
    summary: {
      foundedYear: 2005,
      headmaster: 'Bapak Ahmad Fauzi, S.Pd.I',
    },
    statistics: {
      students: 250,
      alumni: 1200,
      teachers: 20,
      achievements: 45,
      extracurriculars: 10,
    },
    youtubeUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    youtubeThumbnail: 'https://picsum.photos/seed/sd-video/800/450',
    vision: 'Menjadi lembaga pendidikan dasar Islam terdepan yang menghasilkan lulusan berakhlak karimah, cerdas, terampil, dan mandiri.',
    mission: [
      'Menyelenggarakan pendidikan yang berorientasi pada Al-Qur\'an dan Sunnah.',
      'Mengembangkan potensi akademik dan non-akademik siswa secara optimal.',
      'Membentuk pribadi siswa yang beriman, bertaqwa, dan berakhlak mulia.',
      'Menciptakan lingkungan belajar yang kondusif, inovatif, dan menyenangkan.',
    ],
    featuredPrograms: [
      { title: 'Tahfidz Al-Qur\'an', description: 'Program hafalan Al-Qur\'an dengan target minimal 2 juz.', icon: 'book' },
      { title: 'Kelas Bilingual', description: 'Pembelajaran dengan pengantar Bahasa Arab dan Inggris.', icon: 'globe' },
      { title: 'Pramuka Islami', description: 'Kegiatan kepanduan yang menanamkan nilai-nilai keislaman.', icon: 'leaf' },
    ],
    gallery: [
      'https://picsum.photos/seed/sd-gallery1/400/300',
      'https://picsum.photos/seed/sd-gallery2/400/300',
      'https://picsum.photos/seed/sd-gallery3/400/300',
      'https://picsum.photos/seed/sd-gallery4/400/300',
      'https://picsum.photos/seed/sd-gallery5/400/300',
      'https://picsum.photos/seed/sd-gallery6/400/300',
    ],
    achievements: [
      { title: 'Juara 1 Lomba MTQ', level: 'Kabupaten', date: '2023', description: 'Lomba Musabaqah Tilawatil Quran tingkat Kabupaten.', image: 'https://picsum.photos/seed/achieve1/100/100' },
      { title: 'Juara 2 Olimpiade Sains', level: 'Provinsi', date: '2024', description: 'Olimpiade Sains Nasional (OSN) tingkat Provinsi.', image: 'https://picsum.photos/seed/achieve2/100/100' },
    ],
  },
  {
    id: 'smp-minnatul-huda',
    name: 'SMP Minnatul Huda',
    description: 'Pendidikan menengah pertama berbasis pesantren dengan kurikulum terpadu.',
    logo: 'https://imgur.com/4hdcTD7.png',
    accentColor: 'border-green-500',
    textColor: 'text-green-600',
    summary: {
      foundedYear: 2000,
      headmaster: 'Ibu Siti Aminah, M.Pd',
    },
    statistics: {
      students: 400,
      alumni: 2500,
      teachers: 35,
      achievements: 78,
      extracurriculars: 15,
    },
    youtubeUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    youtubeThumbnail: 'https://picsum.photos/seed/smp-video/800/450',
    vision: 'Terwujudnya generasi Rabbani yang unggul dalam prestasi, kokoh dalam imtaq, dan berakhlak mulia.',
    mission: [
      'Mengintegrasikan kurikulum nasional dengan kurikulum kepesantrenan.',
      'Membekali siswa dengan ilmu pengetahuan, teknologi, dan keimanan.',
      'Mencetak kader-kader pemimpin umat yang berwawasan global.',
      'Mengembangkan bakat dan minat siswa melalui kegiatan ekstrakurikuler.',
    ],
    featuredPrograms: [
        { title: 'Kajian Kitab Kuning', description: 'Pendalaman kitab-kitab klasik sebagai dasar ilmu agama.', icon: 'book' },
        { title: 'Science Club', description: 'Kelompok studi untuk pengembangan minat di bidang sains dan teknologi.', icon: 'lab' },
        { title: 'Public Speaking', description: 'Pelatihan pidato dan debat dalam tiga bahasa (Indonesia, Arab, Inggris).', icon: 'speaker' },
    ],
    gallery: [
      'https://picsum.photos/seed/smp-gallery1/400/300',
      'https://picsum.photos/seed/smp-gallery2/400/300',
      'https://picsum.photos/seed/smp-gallery3/400/300',
      'https://picsum.photos/seed/smp-gallery4/400/300',
      'https://picsum.photos/seed/smp-gallery5/400/300',
      'https://picsum.photos/seed/smp-gallery6/400/300',
    ],
    achievements: [
      { title: 'Juara Debat Bahasa Arab', level: 'Nasional', date: '2023', description: 'Kompetisi debat antar SMP Islam Terpadu se-Indonesia.', image: 'https://picsum.photos/seed/achieve3/100/100' },
      { title: 'Medali Emas Robotik', level: 'Internasional', date: '2024', description: 'International Youth Robot Competition di Singapura.', image: 'https://picsum.photos/seed/achieve4/100/100' },
    ],
  },
  {
    id: 'smk-minnatul-huda',
    name: 'SMA / SMK Minnatul Huda',
    description: 'Menyiapkan lulusan yang siap kerja, berwirausaha, dan melanjutkan ke jenjang pendidikan tinggi.',
    logo: 'https://imgur.com/4hdcTD7.png',
    accentColor: 'border-amber-500',
    textColor: 'text-amber-600',
    summary: {
      foundedYear: 1998,
      headmaster: 'Dr. H. Muhammad Yusuf, M.Kom',
    },
    statistics: {
      students: 550,
      alumni: 4000,
      teachers: 50,
      achievements: 120,
      extracurriculars: 20,
    },
    youtubeUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    youtubeThumbnail: 'https://picsum.photos/seed/smk-video/800/450',
    vision: 'Menjadi sekolah unggulan yang menghasilkan lulusan profesional, berjiwa wirausaha, dan berlandaskan nilai-nilai Islam.',
    mission: [
      'Menyelenggarakan pendidikan kejuruan yang relevan dengan kebutuhan industri.',
      'Membina karakter siswa agar menjadi pribadi yang jujur, disiplin, dan bertanggung jawab.',
      'Menjalin kerjasama strategis dengan dunia usaha dan dunia industri (DUDI).',
      'Mengembangkan teaching factory sebagai sarana pembelajaran berbasis produksi.',
    ],
    featuredPrograms: [
      { title: 'Teknik Komputer & Jaringan', description: 'Jurusan yang fokus pada infrastruktur IT, jaringan, dan keamanan siber.', icon: 'computer' },
      { title: 'Agribisnis Tanaman Pangan', description: 'Mempelajari budidaya dan pengelolaan bisnis pertanian modern.', icon: 'leaf' },
      { title: 'Tata Busana', description: 'Mengembangkan kreativitas dalam desain dan produksi busana muslim.', icon: 'tools' },
    ],
    gallery: [
      'https://picsum.photos/seed/smk-gallery1/400/300',
      'https://picsum.photos/seed/smk-gallery2/400/300',
      'https://picsum.photos/seed/smk-gallery3/400/300',
      'https://picsum.photos/seed/smk-gallery4/400/300',
      'https://picsum.photos/seed/smk-gallery5/400/300',
      'https://picsum.photos/seed/smk-gallery6/400/300',
    ],
    achievements: [
      { title: 'Juara 1 LKS Nasional', level: 'Nasional', date: '2023', description: 'Lomba Kompetensi Siswa bidang IT Networking Support.', image: 'https://picsum.photos/seed/achieve5/100/100' },
      { title: 'Best Young Entrepreneur', level: 'Provinsi', date: '2024', description: 'Penghargaan untuk siswa dengan bisnis rintisan terbaik.', image: 'https://picsum.photos/seed/achieve6/100/100' },
    ],
  },
  {
    id: 'yayasan-minnatul-huda',
    name: 'Yayasan Minnatul Huda',
    description: 'Payung lembaga yang menaungi seluruh unit pendidikan dari tingkat dasar hingga menengah.',
    logo: 'https://imgur.com/4hdcTD7.png',
    accentColor: 'border-emerald-600',
    textColor: 'text-emerald-700',
    summary: {
      foundedYear: 1995,
      headmaster: 'KH. Abdullah Karim',
    },
    statistics: {
      students: 1200,
      alumni: 7700,
      teachers: 105,
      achievements: 243,
      extracurriculars: 45,
    },
    youtubeUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    youtubeThumbnail: 'https://picsum.photos/seed/yayasan-video/800/450',
    vision: 'Menjadi pusat peradaban Islam yang unggul dalam pendidikan, dakwah, dan sosial untuk membangun masyarakat madani.',
    mission: [
      'Menyelenggarakan lembaga pendidikan Islam yang berkualitas dan terjangkau.',
      'Melaksanakan kegiatan dakwah dan pengabdian masyarakat secara berkelanjutan.',
      'Mengelola dana umat (zakat, infaq, shadaqah) secara profesional dan amanah.',
      'Membangun sinergi dengan berbagai pihak untuk kemaslahatan umat.',
    ],
    featuredPrograms: [
      { title: 'Program Beasiswa Santri', description: 'Bantuan pendidikan bagi santri berprestasi dan kurang mampu.', icon: 'heart' },
      { title: 'Lembaga Amil Zakat', description: 'Mengelola dan menyalurkan ZISWAF untuk program produktif.', icon: 'briefcase' },
      { title: 'Pengabdian Masyarakat', description: 'Kegiatan sosial, kesehatan, dan dakwah di lingkungan sekitar.', icon: 'users' },
    ],
    gallery: [
      'https://picsum.photos/seed/yayasan-gallery1/400/300',
      'https://picsum.photos/seed/yayasan-gallery2/400/300',
      'https://picsum.photos/seed/yayasan-gallery3/400/300',
      'https://picsum.photos/seed/yayasan-gallery4/400/300',
      'https://picsum.photos/seed/yayasan-gallery5/400/300',
      'https://picsum.photos/seed/yayasan-gallery6/400/300',
    ],
    achievements: [
      { title: 'Lembaga Filantropi Terbaik', level: 'Nasional', date: '2023', description: 'Penghargaan dari Forum Zakat Nasional.', image: 'https://picsum.photos/seed/achieve7/100/100' },
      { title: 'Pesantren Inspiratif', level: 'Provinsi', date: '2022', description: 'Anugerah dari Kantor Wilayah Kementerian Agama.', image: 'https://picsum.photos/seed/achieve8/100/100' },
    ],
  },
];

export const GALLERY_DATA: GalleryItem[] = [
  {
    id: 'fas-1',
    kategori: 'fasilitas',
    judul: 'Masjid Al-Huda',
    deskripsi: 'Pusat kegiatan ibadah dan kajian keislaman bagi seluruh santri dan civitas akademika. Mampu menampung hingga 500 jamaah.',
    gambar: 'https://picsum.photos/seed/masjid/800/600',
  },
  {
    id: 'evt-1',
    kategori: 'event',
    judul: 'Wisuda Tahfidz 2024',
    deskripsi: 'Acara penganugerahan syahadah bagi para santri yang telah menyelesaikan hafalan Al-Qur\'an. Dihadiri oleh wali santri dan tokoh masyarakat.',
    gambar: 'https://picsum.photos/seed/wisuda/800/600',
  },
  {
    id: 'oth-1',
    kategori: 'lainnya',
    judul: 'Kegiatan Bakti Sosial',
    deskripsi: 'Santri berpartisipasi dalam kegiatan bakti sosial di desa sekitar, sebagai bentuk pengabdian kepada masyarakat.',
    gambar: 'https://picsum.photos/seed/baksos/800/600',
  },
  {
    id: 'fas-2',
    kategori: 'fasilitas',
    judul: 'Laboratorium Komputer',
    deskripsi: 'Dilengkapi dengan 40 unit komputer modern untuk mendukung pembelajaran Teknologi Informasi dan Komunikasi.',
    gambar: 'https://picsum.photos/seed/labkom/800/600',
  },
  {
    id: 'fas-3',
    kategori: 'fasilitas',
    judul: 'Asrama Putra',
    deskripsi: 'Lingkungan asrama yang nyaman dan kondusif untuk belajar dan beristirahat, dengan kapasitas 150 santri.',
    gambar: 'https://picsum.photos/seed/asrama/800/600',
  },
  {
    id: 'evt-2',
    kategori: 'event',
    judul: 'Peringatan Hari Santri',
    deskripsi: 'Upacara dan rangkaian perlombaan untuk memeriahkan Hari Santri Nasional, meningkatkan semangat dan kebersamaan.',
    gambar: 'https://picsum.photos/seed/harisantri/800/600',
  },
  {
    id: 'evt-3',
    kategori: 'event',
    judul: 'Lomba Cerdas Cermat',
    deskripsi: 'Kompetisi internal antar unit sekolah untuk mengasah wawasan dan kecepatan berpikir siswa dalam berbagai bidang ilmu.',
    gambar: 'https://picsum.photos/seed/lomba/800/600',
  },
  {
    id: 'oth-2',
    kategori: 'lainnya',
    judul: 'Gotong Royong Kebersihan',
    deskripsi: 'Momen kebersamaan dalam menjaga kebersihan lingkungan pesantren. Menanamkan nilai-nilai kepedulian dan tanggung jawab.',
    gambar: 'https://picsum.photos/seed/gotongroyong/800/600',
  },
  {
    id: 'fas-4',
    kategori: 'fasilitas',
    judul: 'Perpustakaan Terpadu',
    deskripsi: 'Koleksi ribuan buku referensi, fiksi, dan non-fiksi untuk menunjang kegiatan literasi siswa dan guru.',
    gambar: 'https://picsum.photos/seed/perpus/800/600',
  },
  {
    id: 'oth-3',
    kategori: 'lainnya',
    judul: 'Kunjungan Edukatif',
    deskripsi: 'Siswa melakukan kunjungan ke museum sains untuk belajar langsung dan mendapatkan pengalaman baru di luar kelas.',
    gambar: 'https://picsum.photos/seed/kunjungan/800/600',
  },
    {
    id: 'fas-5',
    kategori: 'fasilitas',
    judul: 'Lapangan Olahraga',
    deskripsi: 'Fasilitas multifungsi untuk kegiatan olahraga seperti futsal, basket, dan bulu tangkis.',
    gambar: 'https://picsum.photos/seed/lapangan/800/600',
  },
  {
    id: 'evt-4',
    kategori: 'event',
    judul: 'Outbound & LDKS',
    deskripsi: 'Kegiatan Latihan Dasar Kepemimpinan Siswa di alam terbuka untuk membangun karakter dan kerjasama tim.',
    gambar: 'https://picsum.photos/seed/outbound/800/600',
  }
];